config/routes.rb
SwiftbeansCms::Application.routes.draw do

  resources :services do
    collection do
      post :sign_in
      get :get_customer_menu
      post :save_item
      post :save_add_on
      post :update_item
      post :update_add_on
      post :open_shop
      post :update_merchant
      post :delete_item_add_ons
      get :order_detail
      get :all_order_detail
      post :update_shop_hour
      post :forgot_password
      post :accept_order
      post :change_password
      post :update_bank_account
      post :update_merchant
      post :cancel_order
      post :support_request
      post :complete_order
      post :refund_order
      get :get_notification
      get :get_analytic_main
      get :get_sales_break_down
      get :push_testing
      get :remove_pic
      post :delete_item
      post :delete_add_on
      post :save_sugar
      post :delete_sugar
      post :auto_login
      post :shop_closed
    end
  end

  resources :customer_services do
    collection do
      get :sign_in
      get :get_menu
      post :create_order
      post :add_to_favourite_shop
      post :add_to_favourite_item
      post :add_card_to_customer
      post :update_card_info
      get :get_customer_favorite_shop_items
      post :save_order
      post :update_customer
      post :forgot_password
      get :order_detail
      get :all_order_detail
      post :order_again
      post :support_request
      get :get_shop_distance_away
      post :save_rating
      get :get_shop_status
      get :get_shop_hours
      get :get_charges_ratios
    end
  end

  resources :home

  get "/super_admins" => "super_admin/home#index"
  get "/privacy_policy" => "super_admin/static_pages#privacy_policy"
  get "/terms_and_conditions_user" => "super_admin/static_pages#terms_and_conditions_user"
  get "/terms_and_conditions_merchant" => "super_admin/static_pages#terms_and_conditions_merchant"

  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmation => "users/confirmations",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :unlocks => "users/unlocks",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }

  root :to => "home#index"
  devise_scope :user do
    get "sign_in" => "users/sessions#new"
    get "sign_up" => "users/registrations#new"
    get "sign_out" => "users/sessions#destroy"
    get "change_password" => "users/registrations#change_password"
    post "update_password" => "users/registrations#update_password"
    get "/super_admin" => "users/sessions#new"
    post "merchant_create" => "users/registrations#create"
    post "customer_create" => "users/registrations#create"
    get "account" => "users/registrations#edit"
  end

  namespace :super_admin do

    resources :coupon_codes do
      collection do

        post :create_setting
        get :get_users
        get :search_coupon
      end
    end

    resources :sugars do
      collection do
        get :disable_sugar
      end
    end

    resources :dashboard do
      collection do
        get :get_dashboard
        get :get_active_store
        get :get_recent_orders
      end
    end
    resources :customers do
      collection do
        get :disable_customer
      end
    end
    resources :categories do

    end
    resources :sub_categories do
      collection do
        get :disable_category
      end
    end
    resources :meta_categories
    resources :merchants  do
      collection do
      get :disable_merchant
      get :tax_ratios
      patch :update_tax_ratios
      post :verify_account
        end
    end
    resources :orders
    resources :reviews
    resources :analytics do
      collection do
        get :get_order_stats
        get :get_customer_stats
        get :break_down_by_state
        get :get_analytics
      end
    end
    resources :profiles do
      collection do
        get :profile
        put :update
      end
    end
    resources :transactions do
      collection do
        get :index
        get :charged_shop_transactions
        get :uncharged_shop_transactions
        get :charge_merchants
      end
    end
  end

end

app/controllers/super_admin/analytics_controller.rb
class SuperAdmin::AnalyticsController < SuperAdmin::SuperAdminController
  #before_filter :set_partner, :except => [:create]
  layout "super_admin"

  def index
    @total_revenue =Order.where("total_amount is not null and status = 'accepted'").sum('total_amount')
    @total_sales = Order.where("total_amount is not null").sum('total_amount').round(2)
    @total_customers =User.customers.size
    @new_customers =User.customers.where("Date(users.created_at) >?", Date.today - 7.days).size
    @repeated_customers =User.customers
    @repeated_customers = @repeated_customers.select { |repeated_customer| repeated_customer.orders.size > 1 }.size
    #@drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).where("categories.name = 'HOT DRINKS' or categories.name = 'COLD DRINKS'").size
    @drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'DRINKS' : line_item.item.category.parent.name == 'DRINKS' }.sum(&:quantity)
    @food_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'FOOD' : line_item.item.category.parent.name == 'FOOD' }.sum(&:quantity)
    #@add_ons = OrderAddOn.where("total_price is not null").sum(&:quantity)
    @add_ons = AddOn.all.size
    @total_orders =Order.all.size
    @avg_order = Order.average(:total_amount)
    @avg_order_time = Order.average(:estimated_time)
    @refunded_order = 0
    @refunded_order_amount = 0
    @sales_array= []
    @revenue_array= []
    @order_array = []
    @customer_array = []
    @order_array = []
    @categories = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    12.times.each do |i|
      sales_amount = 0.0
      revenue_amount = 0.0
      orders = Order.where("date_part('month', created_at) = ?", i + 1)
      orders.map { |order| sales_amount += order.total_amount unless order.total_amount.blank? }
      orders.map { |order| revenue_amount += order.total_amount if order.total_amount.present? and order.status == 'accepted' }
      @sales_array << sales_amount
      @revenue_array << revenue_amount
      @customer_array << User.customers.where("date_part('month', users.created_at) = ?", i + 1).size
      @order_array << Order.where("date_part('month', created_at) = ?", i + 1).size
    end
  end

  def get_analytics
    start_date = params[:start_date]
    end_date = params[:end_date]
    @total_revenue =Order.where("total_amount is not null and status = 'accepted' and orders.created_at between ? and ?", start_date, end_date).sum('total_amount')
    @total_sales = Order.where("total_amount is not null and orders.created_at between ? and ?", start_date, end_date).sum('total_amount').round(2)
    @total_customers =User.customers.where("users.created_at between ? and ?", start_date, end_date).size
    @new_customers =User.customers.where(" Date(users.created_at) >?", Date.today - 7.days).size
    @repeated_customers =User.customers
    @repeated_customers = @repeated_customers.select { |repeated_customer| repeated_customer.orders.size > 1 }.size
    #@drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).where("categories.name = 'HOT DRINKS' or categories.name = 'COLD DRINKS'").size
    @drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'DRINKS' : line_item.item.category.parent.name == 'DRINKS' }.sum(&:quantity)
    @food_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'FOOD' : line_item.item.category.parent.name == 'FOOD' }.sum(&:quantity)
    #@add_ons = OrderAddOn.where("total_price is not null").sum(&:quantity)
    @add_ons = AddOn.all.size
    @total_orders =Order.where("created_at between ? and ?", start_date, end_date).size
    @avg_order = Order.average(:total_amount)
    @avg_order_time = Order.average(:estimated_time)
    @refunded_order = 0
    @refunded_order_amount = 0
    @sales_array= []
    @revenue_array= []
    @order_array = []
    @customer_array = []
    @order_array = []
    @categories = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    12.times.each do |i|
      sales_amount = 0.0
      revenue_amount = 0.0
      orders = Order.where("date_part('month', created_at) = ?", i + 1)
      orders.map { |order| sales_amount += order.total_amount unless order.total_amount.blank? }
      orders.map { |order| revenue_amount += order.total_amount if order.total_amount.present? and order.status == 'accepted' }
      @sales_array << sales_amount
      @revenue_array << revenue_amount
      @customer_array << User.customers.where("date_part('month', users.created_at) = ?", i + 1).size
      @order_array << Order.where("date_part('month', created_at) = ?", i + 1).size
    end
    render :partial => "/super_admin/analytics/analytic_list"
  end

  def get_order_stats
    if params[:id].blank?
      @total_sales = Order.where("total_amount is not null").sum('total_amount')
      @total_orders =Order.all.size
      @avg_order = Order.average(:total_amount)
      @avg_order_time = Order.average(:estimated_time)
      @refunded_order = 0
      @refunded_order_amount = 0
    else
      @shop = Shop.find_by_user_id(params[:id])
      @total_sales = Order.where("total_amount is not null and shop_id = ?", @shop.id).sum('total_amount')
      @total_orders =Order.where(:shop_id => @shop.id).size
      @avg_order = Order.where(:shop_id => @shop.id).average(:total_amount)
      @avg_order_time = Order.where(:shop_id => @shop.id).average(:estimated_time)
      @refunded_order = 0
      @refunded_order_amount = 0
    end

    render :partial => "super_admin/analytics/orders"

  end

  def get_customer_stats
    if params[:id].blank?
      @total_customers =User.customers.size
      @new_customers =User.customers.where("Date(users.created_at) >?", Date.today - 7.days).size
      @repeated_customers =User.customers
      @repeated_customers = @repeated_customers.select { |repeated_customer| repeated_customer.orders.size > 1 }.size
      @drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'DRINKS' : line_item.item.category.parent.name == 'DRINKS' }.sum(&:quantity)
      @food_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'FOOD' : line_item.item.category.parent.name == 'FOOD' }.sum(&:quantity)
      #@add_ons = OrderAddOn.where("total_price is not null").sum(&:quantity)
      @add_ons = AddOn.all.size
    else
      @shop = Shop.find_by_user_id(params[:id])
      @total_customers = @shop.orders.group_by { |order| order.user_id }.size
      @new_customers = @shop.orders.where("Date(created_at) >?", Date.today - 7.days).group_by { |order| order.user_id }.size
      @repeated_customers =@shop.orders.group_by { |order| order.user }.select { |repeated_customer| repeated_customer.orders.size > 1 }.size
      @drinks_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).where("items.shop_id=?", @shop.id).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'DRINKS' : line_item.item.category.parent.name == 'DRINKS' }.sum(&:quantity)
      @food_bought = OrderLineItem.includes(:item_size => [:item => [:category]]).where("items.shop_id=?", @shop.id).select { |line_item| line_item.item.blank? ? line_item.item_size.item.category.parent.name == 'FOOD' : line_item.item.category.parent.name == 'FOOD' }.sum(&:quantity)
      #@add_ons = OrderAddOn.includes(:order_line_item => [:order]).where("orders.shop_id=? and order_line_items.total_price is not null", @shop.id).sum(&:quantity)
      @add_ons = @shop.add_ons.size
    end

    render :partial => "super_admin/analytics/customers"

  end

  def break_down_by_state
    @state_array =[]
    @shops = Shop.all.group_by { |shop| shop.state }.each do |state, shops|
      customers = 0
      sales = 0
      orders = []
      shops.each do |shop|
        orders += shop.orders
      end
      unless orders.blank?
        customers = orders.group_by { |order| order.user_id }.size
        orders.select { |order| sales+= order.total_amount.blank? ? 0 : order.total_amount}
      end
      h = {:state => state, :orders => orders.size, :customers => customers, :sales => sales}
      @state_array << h
      #@state_hash[state]
      @state_array.each_with_index do |ar|
        puts "SSS", ar[:orders].inspect

      end
    end
  end

end

app/controllers/super_admin/categories_controller.rb
class SuperAdmin::CategoriesController < SuperAdmin::SuperAdminController
  add_breadcrumb "CATEGORIES", "/super_admin/categories"
  layout "super_admin"

  def index
    @categories = Category.where(:parent_id => nil)

  end

  def new
    @category = Category.new
    #render :layout => false
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully Added."
      render :json => {:success => true, :url => super_admin_categories_path}.to_json
    else
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
    #render :layout => false
  end

  def update
    @category = Category.find_by_id(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Category was successfully Added."
      render :json => {:success => true, :url => super_admin_categories_path}.to_json
    else
      @category = @user.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :parent_type)
  end


end

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < SuperAdmin::SuperAdminController
  #before_filter :set_partner, :except => [:create]
  layout "super_admin"

  def index
    #@customers_count = User.customers.size
    #@drivers_count = User.drivers.size
    #@delivered_jobs_count = User.total_delivered_jobs.size
    #@ziply_revenue = TransactionHistory.sum(:ziply_revenue) # => 4562
    #@driver_revenue = TransactionHistory.sum(:driver_amount) # => 4562
    @stores = User.merchants.size
    @new_stores = User.merchants.where("Date(users.created_at) > ?", Date.today - 7.day).size
    @customers = User.customers.size
    @new_customers = User.customers.where("Date(users.created_at) > ?", Date.today - 7.day).size
    @orders = Order.all.size
    @new_orders = Order.where("Date(created_at) > ?", Date.today - 7.day).size
    @sale = Order.where(:status => 'accepted').sum('total_amount')
    @today_sale = Order.where("Date(created_at) = ? and status= ?", Date.today, 'accepted').sum('total_amount')
    @reviews = Review.all.size
    @today_reviews = Review.where("Date(created_at) > ?", Date.today - 7.day).size
    @active_stores = Shop.all.sort_by { |shop| shop.orders.size }
    @recent_orders = Order.order("created_at desc")
  end

  def get_dashboard
    start_date = params[:start_date]
    end_date = params[:end_date]
    @stores = User.merchants.where("users.created_at between ? and ?", start_date, end_date).size
    @new_stores = User.merchants.where("Date(users.created_at) > ? ", Date.today - 7.day).size
    @customers = User.customers.where("users.created_at between ? and ?", start_date, end_date).size
    @new_customers = User.customers.where("Date(users.created_at) > ?", Date.today - 7.day).size
    @orders = Order.where("orders.created_at between ? and ?", start_date, end_date).size
    @new_orders = Order.where("Date(created_at) > ?", Date.today - 7.day).size
    @sale = Order.where("orders.created_at between ? and ? and status =?", start_date, end_date, 'accepted').sum('total_amount')
    @today_sale = Order.where("Date(created_at) = ? and status= ?", Date.today, 'accepted').sum('total_amount')
    @reviews = Review.where("reviews.created_at between ? and ?", start_date, end_date).size
    @today_reviews = Review.where("Date(created_at) > ?", Date.today - 7.day).size
    render :partial => "/super_admin/dashboard/dash_list"
  end

  def get_active_store
    start_date = params[:start_date]
    end_date = params[:end_date]
    @active_stores = Shop.includes(:orders).where("orders.created_at between ? and ?", start_date, end_date.to_date + 1.day).sort_by { |shop| shop.orders.size }
    render :partial => "/super_admin/dashboard/active_stores"
  end

  def get_recent_orders
    start_date = params[:start_date]
    end_date = params[:end_date]
    @recent_orders = Order.where("orders.created_at between ? and ?", start_date, end_date.to_date + 1.day).order("created_at desc")
    render :partial => "/super_admin/dashboard/recent_orders"
  end

end

app/helpers/super_admin/coupon_codes_helper.rb
module SuperAdmin::CouponCodesHelper
end

app/helpers/super_admin/static_pages_helper.rb
module SuperAdmin::StaticPagesHelper
end

app/helpers/super_admin/transactions_helper.rb
module SuperAdmin::TransactionsHelper
end

app/views/super_admin/coupon_codes/_coupon_list.html.erb
<table class="table table-striped table-bordered table-hover" id="customer_table">
  <thead>
  <tr>
    <th>
      Coupon Code
    </th>
    <th>
      Value
    </th>
    <th>
      Valid From
    </th>
    <th>
      Valid To
    </th>
    <th>
      Sent By
    </th>
    <th>
      Send To Users
    </th>
    <th>
      Per User
    </th>
    <th>
      Per Coupon
    </th>
    <th>
      Used
    </th>
    <th>
      Status
    </th>
  </tr>
  </thead>
  <% unless @coupon_codes.blank? %>
      <tbody>
      <% @coupon_codes.each_with_index do |coupon_code, index| %>
          <tr class="odd gradeX">

            <td>
              <%= coupon_code.code %>
            </td>
            <td>
              <% if coupon_code.coupon_type == "amount" %>
                  $<%= coupon_code.coupon_value %>
              <% else %>
                  <%= coupon_code.coupon_value %>%
              <% end %>
            </td>
            <td>
              <%= coupon_code.valid_from.strftime("%m/%d/%Y") %>
            </td>
            <td>
              <%= coupon_code.valid_to.strftime("%m/%d/%Y") %>
            </td>
            <td>
              Admin
            </td>
            <td>
              <%= "users"%>
              <%#= coupon_code.promotion_code_user_id == 0 ? "All" : "coupon_code.promotion_code_user.name" %>
            </td>
            <td>
              <%= coupon_code.per_user == 0 ? "Unlimited" : coupon_code.per_user %>
            </td>
            <td>
              <%= coupon_code.per_coupon == 0 ? "Unlimited" : coupon_code.per_coupon %>
            </td>
            <td>
              0
            </td>
            <td>
              <%= coupon_code.get_status(coupon_code) %>
            </td>

          </tr>
      <% end %>
      </tbody>
  <% end %>
</table>
<div class="pager_outer" style="float: left;margin: 15px 0 0 -10px">
  <%= will_paginate @coupon_codes %>
</div>
<script type="text/javascript">
    var pre_page = "";
    $(".pagination a").click(function () {

        split_array = this.toString().split("page=");
        split_array[1].split("&")[0];
        page = split_array[1].split("&")[0];
        if (pre_page != page) {
            pre_page = page;
            $('.shadow').show();
            $('.ajax_loader').show();
            var url = "/super_admin/coupon_codes?page=" + page;
            $.get(url, function (html) {
                $('.shadow').hide();
                $('.ajax_loader').hide();
                $('#coupon_list').html(html).fadeIn('slow');
//                $('#snaptarget').html($(html).find('#snaptarget').html());
//                $('.pagination').html($(html).find('.pagination'));
//                $('.shadow').hidet();
//                $('.ajax_loader').hide();
//                $('#merchant_list').html(response).fadeIn('slow');
            });
        }
        return false;
    });
</script>

app/views/super_admin/coupon_codes/_list.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box grey-cascade">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-globe"></i>Create Customer Coupons Code
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
        </div>
      </div>
      <div class="portlet-body">
        <%= form_for(@coupon_code, :url => super_admin_coupon_codes_path, :html => {:id => "coupon_code_list", :onsubmit => "return false;"}, :method => "post") do |f| %>
            <%= f.hidden_field :is_send, :value => true %>
            <%= f.hidden_field :is_setting, :value => true %>
            <%= f.hidden_field :promotion_code_user_type, :value => "User" %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :code, :value => SecureRandom.hex(3) %>
            <div class="form-body">
              <div class="row" id="errors"></div>
              <div class="row">
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Coupon Amount</label>
                    <%= f.text_field :coupon_value, :autofocus => true, :class => "form-control", :placeholder => "Name" %>
                  </div>
                </div>
                <!--/span-->
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Coupon Type</label>
                    <%#= f.text_field :coupon_type, :class => "form-control", :placeholder => "Name" %>
                    <%= select_tag("coupon_code[coupon_type]", options_for_select([["Float Amount", "amount"], ["percentage", "Percentage"]]), :class => "form-control") %>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Valid from dates</label>
                    <%= f.text_field :valid_from, :class => "form-control date-picker", :placeholder => "Valid from dates" %>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Valid to dates</label>
                    <%= f.text_field :valid_to, :class => "form-control date-picker", :placeholder => "Valid to dates" %>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Per User</label>
                    <%= f.text_field :per_user, :value => "", :class => "form-control", :placeholder => "" %>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Per Coupon</label>
                    <%= f.text_field :per_coupon, :value => "", :class => "form-control", :placeholder => "" %>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Number of shares</label>
                    <%= f.text_field :number_to_share, :value => "", :class => "form-control", :placeholder => "" %>
                  </div>
                </div>
                <!--/span-->
              </div>

              <div class="row">
                <div class="col-md-2">
                  <div class="form-group">
                    <label class="control-label">Users</label>
                    <%= select_tag("coupon_code[coupon_group]", options_for_select([["None", "none"],["All", "all"], ["Customers", "customers"]]), :class => "form-control") %>
                  </div>
                </div>
                <div id="user_ddl">
                  <%= render :partial => "super_admin/coupon_codes/user_drop_down" %>
                </div>

              </div>

              <div class="form-actions">
                <button type="button" class="btn blue" id="save_btn">Create Code</button>
                <button type="button" class="btn default" id="save-btn-email">CREAT BUT DONT SEND</button>
              </div>

            </div>
        <% end %>
      </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
  </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        $('.date-picker').datepicker({
            rtl: Metronic.isRTL(),
            autoclose: true,
            format: 'mm-dd-yyyy'
        });
        var placeholder = " ";
        $("input[type=text],input[type=email],input[type=password]").focus(function () {
            placeholder = $(this).attr("placeholder");
            return $(this).attr("placeholder", " ");
        });
        $("input[type=text],input[type=email],input[type=password]").blur(function () {
            if ($(this).val() === "") {
                return $(this).attr("placeholder", placeholder);
            }
        });
        $("#coupon_code_list").validate({
            rules: {
                "coupon_code[coupon_value]": {
                    required: true,
                    number: true
                },
                "coupon_code[coupon_type]": {
                    required: true
                },
                "coupon_code[valid_from]": {
                    required: true
                },
                "coupon_code[valid_to]": {
                    required: true
                },
                "coupon_code[per_user]": {
                    number: true
                },
                "coupon_code[per_coupon]": {
                    number: true
                }
            }
        });
        $("#save_btn").click(function () {
            if (!$("#coupon_code_list").valid()) {
                return false;
            } else {
                $("#ajax_loader").show();
                $(".shadow").show();
                $("#coupon_code_list").ajaxSubmit({
                    beforeSubmit: function (a, f, o) {
                        o.dataType = 'json';
                    },
                    success: function (data) {
                        console.log(data.success);
                        if (data.success == true) {
//                        window.location.reload();
                            window.location.href = data.url;
                        } else {
                            $("#errors").html(data.html)
                        }
                        $("#ajax_loader").hide();
                        $(".shadow").hide();
                    },
                    error: function (data) {
                        hudMsg("something went wrong");
                    }
                });
            }
        });

        $("#save-btn-email").click(function () {
            $("#coupon_code_is_send").val(false);
            if (!$("#coupon_code_list").valid()) {
                return false;
            } else {
                $("#ajax_loader").show();
                $(".shadow").show();
                $("#coupon_code_list").ajaxSubmit({
                    beforeSubmit: function (a, f, o) {
                        o.dataType = 'json';
                    },
                    success: function (data) {
                        console.log(data.success);
                        if (data.success == true) {
//                        window.location.reload();
                            window.location.href = data.url;
                        } else {
                            $("#errors").html(data.html)
                        }
                        $("#ajax_loader").hide();
                        $(".shadow").hide();
                    },
                    error: function (data) {
                        hudMsg("something went wrong");
                    }
                });
            }
        });

    });


    $("#coupon_code_coupon_group").change(function () {
        if ($("#coupon_code_coupon_group").val() == "none") {
           return false
        }
        $('.shadow').show();
        $('.ajax_loader').show();
        $.ajax({
            url: '/super_admin/coupon_codes/get_users?id=' + $("#coupon_code_coupon_group").val(),
            type: 'get',
            dataType: 'html',
            processData: false,
            success: function (data) {
                $("#user_ddl").html(data);
                $("#ajax_loader").hide();
                $(".shadow").hide();
            }
        });
    });

    function close_pop_up() {
        $('.z_light_box').hide();
    }

</script>

app/views/super_admin/coupon_codes/_user_drop_down.html.erb
<div class="col-md-2">
  <div class="form-group">
    <label class="control-label">User Name</label>
    <%= select_tag("coupon_code[promotion_code_user_id]", options_for_select(["All", ""] + @users.all.map { |user| [user.email, user.id] }),:multiple => true, :class => "chosen-select") %>
  </div>
</div>
<script>
    $(".chosen-select").chosen({width: "95%"});
</script>