config/routes.rb
SwiftbeansCms::Application.routes.draw do

  resources :services do
    collection do
      post :sign_in
      get :get_customer_menu
      post :save_item
      post :save_add_on
      post :update_item
      post :update_add_on
      post :open_shop
      post :update_merchant
      post :delete_item_add_ons
      get :order_detail
      get :all_order_detail
      post :update_shop_hour
      post :forgot_password
      post :accept_order
      post :change_password
      post :update_bank_account
      post :update_merchant
      post :cancel_order
      post :support_request
      post :complete_order
      post :refund_order
      get :get_notification
      get :get_analytic_main
      get :get_sales_break_down
      get :push_testing
      get :remove_pic
      post :delete_item
      post :delete_add_on
      post :save_sugar
      post :delete_sugar
      post :auto_login
      post :shop_closed
    end
  end

  resources :customer_services do
    collection do
      get :sign_in
      get :get_menu
      post :create_order
      post :add_to_favourite_shop
      post :add_to_favourite_item
      post :add_card_to_customer
      post :update_card_info
      get :get_customer_favorite_shop_items
      post :save_order
      post :update_customer
      post :forgot_password
      get :order_detail
      get :all_order_detail
      post :order_again
      post :support_request
      get :get_shop_distance_away
      post :save_rating
      get :get_shop_status
      get :get_shop_hours
      get :get_charges_ratios
    end
  end

  resources :home

  get "/super_admins" => "super_admin/home#index"
  get "/privacy_policy" => "super_admin/static_pages#privacy_policy"
  get "/terms_and_conditions_user" => "super_admin/static_pages#terms_and_conditions_user"
  get "/terms_and_conditions_merchant" => "super_admin/static_pages#terms_and_conditions_merchant"

  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmation => "users/confirmations",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :unlocks => "users/unlocks",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }

  root :to => "home#index"
  devise_scope :user do
    get "sign_in" => "users/sessions#new"
    get "sign_up" => "users/registrations#new"
    get "sign_out" => "users/sessions#destroy"
    get "change_password" => "users/registrations#change_password"
    post "update_password" => "users/registrations#update_password"
    get "/super_admin" => "users/sessions#new"
    post "merchant_create" => "users/registrations#create"
    post "customer_create" => "users/registrations#create"
    get "account" => "users/registrations#edit"
  end

  namespace :super_admin do

    resources :coupon_codes do
      collection do

        post :create_setting
        get :get_users
        get :search_coupon
      end
    end

    resources :sugars do
      collection do
        get :disable_sugar
      end
    end

    resources :dashboard do
      collection do
        get :get_dashboard
        get :get_active_store
        get :get_recent_orders
      end
    end
    resources :customers do
      collection do
        get :disable_customer
      end
    end
    resources :categories do

    end
    resources :sub_categories do
      collection do
        get :disable_category
      end
    end
    resources :meta_categories
    resources :merchants  do
      collection do
      get :disable_merchant
      get :tax_ratios
      patch :update_tax_ratios
      post :verify_account
        end
    end
    resources :orders
    resources :reviews
    resources :analytics do
      collection do
        get :get_order_stats
        get :get_customer_stats
        get :break_down_by_state
        get :get_analytics
      end
    end
    resources :profiles do
      collection do
        get :profile
        put :update
      end
    end
    resources :transactions do
      collection do
        get :index
        get :charged_shop_transactions
        get :uncharged_shop_transactions
        get :charge_merchants
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "super_admin_non_login"

  #def index
  #
  #
  #  #Shop.all.each do |shop|
  #  #
  #  #  puts "CC", custom.user_id
  #  #end
  #
  #  #@user = User.find(3)
  #  #favourite_shop_ids = @user.favourites.map { |favourite| favourite.shop if favourite.shop }
  #  #render :json => {:success => "true",
  #  #                 :data => {
  #  #                     :customer => "s",
  #  #                     :shops => favourite_shop_ids.blank? ? [] : favourite_shop_ids.map { |shop| {:id => shop.id, :name => shop.name, :phone => shop.phone, :address => shop.address, :latitude => shop.latitude, :longitude => shop.longitude, :hours => shop.hours, :status => shop.status, :reviews_count => shop.reviews.size, :average_rating => shop.average_rating, :is_favourite => favourite_shop_ids.include?(shop.id) ? true : false} }
  #  #                     #:favourite_shops => @user.favourites.map { |favourite| {:id => favourite.id, :shop_id => favourite.shop.id, :name => favourite.shop.name, :phone => favourite.shop.phone, :address => favourite.shop.address, :latitude => favourite.shop.latitude, :longitude => favourite.shop.longitude, :hours => favourite.shop.hours, :status => favourite.shop.status, :reviews_count => favourite.shop.reviews.size, :average_rating => favourite.shop.average_rating} if favourite.shop }
  #  #                 }
  #  #}
  #  #puts "CC", favourite_shop_ids.inspect
  #  #  ss
  #  if current_user.present?
  #    redirect_to super_admin_merchants_path
  #  end
  #end

  def index
    @user =User.new
    if current_user.present?
      redirect_to super_admin_merchants_path
    end
  end


end

app/controllers/super_admin/home_controller.rb
class SuperAdmin::HomeController < SuperAdmin::SuperAdminController

  def index
    redirect_to super_admin_categories_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_for(@user, :as => :user, :url => session_path(@user), :html => {:class => "sign_in-form", :novalidate => "novalidate"}) do |f| %>
    <!--<form method="post" action="index.html" class="login-form" novalidate="novalidate">-->
    <h3 class="form-title">Login to your account</h3>

    <div class="alert alert-danger display-hide">
      <button data-close="alert" class="close"></button>
			<span>
			Enter any username and password. </span>
    </div>
    <div class="form-group">
      <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
      <label class="control-label visible-ie8 visible-ie9">Username</label>

      <div class="input-icon">
        <i class="fa fa-user"></i>
        <!--<input type="text" name="username" placeholder="Username" autocomplete="off" class="form-control placeholder-no-fix">-->
        <%= f.email_field :email, :autofocus => true, :class => "form-control placeholder-no-fix", :placeholder => "Email Address *" %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Password</label>

      <div class="input-icon">
        <i class="fa fa-lock"></i>
        <%= f.password_field :password, :class => "form-control placeholder-no-fix", :placeholder => "Password *" %>
        <!--<input type="password" name="password" placeholder="Password" autocomplete="off" class="form-control placeholder-no-fix">-->
      </div>
    </div>
    <div class="form-actions">

      <button class="btn green pull-right" type="submit" id="login_and_continue">
        Login <i class="m-icon-swapright m-icon-white"></i>
      </button>
    </div>
<% end %>



<script type="text/javascript">

    $('.sign_in-form').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: false, // do not focus the last invalid input
        rules: {
            "user[email]": {
                required: true
            },
            "user[password]": {
                required: true
            },
            remember: {
                required: false
            }
        },

        messages: {
            "user[email]": {
                required: "Email is required."
            },
            "user[password]": {
                required: "Password is required."
            }
        },

        invalidHandler: function (event, validator) { //display error alert on form submit
            $('.alert-danger', $('.login-form')).show();
        },

        highlight: function (element) { // hightlight error inputs
            $(element)
                    .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function (label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function (error, element) {
            error.insertAfter(element.closest('.input-icon'));
        }
    });


    $('.sign_in-form').keypress(function (e) {
        if (e.which == 13) {
            if ($('.sign_in-form').validate().form()) {
                submit_form();
            }
            return false;
        }
    });

    $("#login_and_continue").click(function () {
        if ($('.sign_in-form').validate().form()) {
            submit_form();
        }
        return false;
    });

    function submit_form() {
        $("#ajax_loader").show();
        $(".shadow").show();
        $(".sign_in-form").ajaxSubmit({
            beforeSubmit: function (a, f, o) {
                o.dataType = 'json';
            },
            success: function (data) {
                console.log(data.success);
                if (data.success == true) {
                    window.location.href = "/super_admin/dashboard";
                } else {
                    $(".alert-danger").show();
                    $(".alert-danger span").html(data.errors);
                }
                $("#ajax_loader").hide();
                $(".shadow").hide();
            },
            error: function (data) {
                window.location.reload();
            }
        });
    }
</script>